jwt:
  secret: "[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$"

# To remove the white label error page we can do that in 2 different ways.

# In Servlet we give default servlet 404 error page, which will override the default white label error page.

# by adding error: whitelabel: enabled: false
# we can disable the whitelabel 404 error and servlet will give its default 404 page.

server:
  port: 8081
  # error:
  #   whitelabel:
  #     enabled: false

# In spring we can do the following

# mvc: throw-exception-if-no-handler-found: true
# this will throw exception if there no url or the endpoint found when we hit any random endpoint.

#  web: resources: add-mappings: false
# this will remove the default mapping to the whitelabel error page.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_jwt_support_portal
    password: Kshitiz@123
    username: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # mvc:
  #   throw-exception-if-no-handler-found: true

  # web:
  #   resources:
  #     add-mappings: false
